[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.4.0"
tinyaudio = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0.98"
glam = "0.30.3"

[[bin]]
name = "audio"
path = "src/main.rs"

[lib]
name = "audio"
path = "src/lib.rs"