[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[dependencies]
tinyaudio = "1"
anyhow = "1.0.98"
glam = "0.30.3"

[[bin]]
name = "audio"
path = "src/main.rs"

[lib]
name = "audio"
path = "src/lib.rs"